/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../src/app.module';
import * as import2 from 'mwl-example-ng2-module/dist/src/demo.module';
import * as import3 from '@angular/core/src/di/injector';
import * as import4 from './app.component.ngfactory';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _DemoModule_0:import2.DemoModule;
  _AppModule_1:import1.AppModule;
  constructor(parent:import3.Injector) {
    super(parent,[import4.AppComponentNgFactory],[import4.AppComponentNgFactory]);
  }
  createInternal():import1.AppModule {
    this._DemoModule_0 = new import2.DemoModule();
    this._AppModule_1 = new import1.AppModule();
    return this._AppModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.DemoModule)) { return this._DemoModule_0; }
    if ((token === import1.AppModule)) { return this._AppModule_1; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);